# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml

#config.load_autoconfig()

c.url.start_pages = ["https://google.com"]
c.url.default_page = "https://google.com"
c.url.searchengines = {"DEFAULT": "https://google.com/search?q={}"}
c.downloads.location.directory = "~/Downloads"

config.bind("z", "spawn mpv {url}")
config.bind("Z", "hint links spawn mpv {hint-url}")
config.bind("xa", "spawn --userscript youtube_mp3_downloader.sh")
config.bind("Xa", "hint links userscript youtube_mp3_downloader.sh")
config.bind("xv", "spawn --userscript youtube_downloader.sh")
config.bind("Xv", "hint links userscript youtube_downloader.sh")
